name: NN Internal API

on:
  push:
    paths:
    - 'NN/API**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.10'

    - name: Install dependencies
      working-directory: ./NN/API
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip freeze > requirements.txt

    - name: Build
      working-directory: ./NN/API
      run: python -m py_compile ./main.py

    - name: Syntax checker
      working-directory: ./NN/API
      run: |
        pip install flake8
        flake8 . --max-line-length 150
