name: Web

on:
  push:
    paths:
    - 'Web/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '17.x'

    - name: Install dependencies
      run: npm install # add dependencies here

    - name: Build
      run: npm run build --if-present

    - name: Run the tests
      run: npm test
